- name: My first play
  hosts: faceit.local
  remote_user: pi
  become: true
  gather_facts: False #To disable first task
  tasks:
    - name: Install PIP3
      ansible.builtin.apt:
        name: python3-pip
        state: present
    - name: Install GIT
      ansible.builtin.apt:
        name: git
        state: present
    - name: Install Android Debug Bridge (ADB)
      ansible.builtin.apt:
        name: android-sdk-platform-tools
        state: present
    - name: Clone single branch from repo
      ansible.builtin.git:
        repo: https://github.com/CaishenNefri/csgo-faceit-monitor-matches.git
        dest: /home/smsNotify
        single_branch: true
        version: feature/smsNotification
    - name: Execute permission for smsApp - python requriments
      file: dest=/home/smsNotify/smsNotifyApplication/requirements.txt mode=a+x
    - name: Execute permission for smsApp - python main.py
      file: dest=/home/smsNotify/smsNotifyApplication/main.py mode=a+x
    - name: Install smsNotify app requriments
      ansible.builtin.pip:
        requirements: /home/smsNotify/smsNotifyApplication/requirements.txt