trigger:
- dev

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscriptionEndpoint: AzureRM
  WebAppName: app-service-73638

steps:
# - task: "AzureRMWebAppDeployment@4"
#   displayName: Azure App Service Deploy
#   inputs:
#     WebAppKind: webAppLinux
#     ConnectedServiceName: $(azureSubscriptionEndpoint)
#     WebAppName: $(WebAppName)
#     Package: $(Build.SourcesDirectory)\.appSerivcePython\

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'ls ''$(Build.SourcesDirectory)'''
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: 'Get-Content -Path $(Build.SourcesDirectory)\notes.md'

- task: AzureRMWebAppDeployment@4
  inputs:
    ConnectedServiceName: $(azureSubscriptionEndpoint)
    WebAppKind: webAppLinux
    WebAppName: $(WebAppName)
    Package: '$(Build.SourcesDirectory)/.appSerivcePython'

- task: PublishBuildArtifacts@1